# Generated by Django 5.0.4 on 2024-05-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('enlace', models.TextField()),
                ('ambiente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autenticacion.persona')),
                ('celular', models.CharField(max_length=255)),
            ],
            bases=('autenticacion.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autenticacion.persona')),
                ('correo', models.CharField(max_length=255)),
            ],
            bases=('autenticacion.persona',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autenticacion.persona')),
                ('foto', models.TextField()),
            ],
            bases=('autenticacion.persona',),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('contrasenha', models.CharField(max_length=255)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='autenticacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='autenticacion.carrera')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='autenticacion.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='autenticacion.asesoria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='autenticacion.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='asesoria',
            name='estudiantes',
            field=models.ManyToManyField(through='autenticacion.Reserva', to='autenticacion.estudiante'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('asesoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='autenticacion.asesoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='autenticacion.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='autenticacion.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='autenticacion.profesor')),
            ],
        ),
    ]
