# Generated by Django 5.0.4 on 2024-05-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoActual', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
