# Generated by Django 5.0.4 on 2024-06-02 16:02

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_singleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=app.models.Documento.generar_nombre_unico)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.seccion')),
            ],
        ),
    ]
