# Generated by Django 5.0.6 on 2024-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_documento_historial_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaDeSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
    ]
