# Generated by Django 5.0.6 on 2024-06-11 01:41

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_preguntadeseguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='pregunta',
            field=models.ForeignKey(default=app.models.PreguntaDeSeguridad.get_default_pregunta, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='app.preguntadeseguridad'),
        ),
    ]
