# Generated by Django 5.0.6 on 2024-06-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cuenta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='app.preguntadeseguridad'),
        ),
    ]
