# Generated by Django 5.0.6 on 2024-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cuenta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='respuesta',
            field=models.CharField(default='nina', max_length=255),
        ),
    ]
