# Generated by Django 5.0.4 on 2024-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cuenta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.FileField(default='imagenes/foto_default.png', upload_to='imagenes/'),
        ),
    ]
