# Generated by Django 5.0.4 on 2024-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_asesoria_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='correo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
