# Generated by Django 5.0.6 on 2024-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profesor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.FileField(default='imagenes/foto_default.png', upload_to='imagenes/'),
        ),
    ]
